version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  back_end:
    build: './back_end'
    command: ["./scripts/wait_for_postgres.sh", "npm", "run", "dev"]
    volumes:
      - ./back_end:/app
      - '/app/node_modules'
    ports:
      - "3001:3001"
    environment:
      DATABASE_PASSWORD: postgres://root:root@db:5432/silver_sockets
      TEST_DATABASE_PASSWORD: postgres://root:root@db:5432/silver_sockets_test
      CIVIS_SERVICE_PORT: 3001
      PORT: 3001
    env_file:
      - ./secrets/GOOGLE_OAUTH
      - ./secrets/FACEBOOK_OAUTH
      - ./secrets/TWITTER_OAUTH
    depends_on:
      - db
  front_end:
    build: './front_end'
    command: ["npm", "start"]
    volumes:
      - ./front_end:/app
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      CI: "true"
